#!/usr/bin/with-contenv bash
if [ "$enableQueueCleaner" != "true" ]; then
	echo "QueueCleaner Script disabled, enable by setting parameter: enableQueueCleaner=true"
	sleep infinity
fi

echo "Waiting for Lidarr to startup..."
sleep 2m
echo "Starting QueueCleaner Script...."
for (( ; ; )); do
	let i++
	   
	bash /config/extended/scripts/QueueCleaner.bash
	
	echo "Script sleeping for 15 minutes..."
	sleep 15m
done

exit
