FROM linuxserver/lidarr:amd64-nightly
LABEL maintainer="RandomNinjaAtk"

RUN \
	echo "************ install packages ************" && \
	apk add  -U --update --no-cache \
		flac \
		beets \
		jq \
		git \
		gcc \
		ffmpeg \
		python3-dev \
		libc-dev \
		py3-pip \
		yt-dlp && \
	echo "************ install python packages ************" && \
	pip install \
		yq \
		r128gain \
		tidal-dl \
		deemix

# ports and volumes
EXPOSE 8686
VOLUME /config /music /music-videos /downloads
