#!/usr/bin/with-contenv bash
if [ "$configureLidarrWithOptimalSettings" != "true" ]; then
	echo "AutoConfig.bash Script disabled, enable by setting parameter: configureLidarrWithOptimalSettings=true"
	sleep infinity
fi
echo "Waiting for Lidarr to startup..."
sleep 2m
echo "Starting AutoConfig.bash Script...."
bash /config/extended/scripts/AutoConfig.bash
sleep infinity
exit
