#!/usr/bin/with-contenv bash
if [ "$enableAudioScript" = "true" ]; then
	echo "Starting Audio.sh in 2 min..."
	sleep 2m
	bash /config/extended/scripts/Audio.sh
else
	echo "Automatic Start Disabled, to enable set enableAudioScript=true"
	echo "Manually run using this command:"
	echo "bash /config/extended/scripts/Audio.sh"
	sleep infinity
fi

exit $?
